#' Create a submodular graph comprised of multiple subgraphs, each built as a modular graph; see make_modular_graph for details
#' @param g.type a character, the graph type; 'er' for Erdos-Renyi or 'sf' for scale-free
#' @param n.mods an integer, the number of modules in the output graph
#' @param n.mod.links an integer, the number of edges between each pair of modules
#' @param n.sg an integer, the number of subgraphs to create
#' @param n.sg.nodes an integer, the number of nodes in each subgraph
#' @param n.sg.links an integer, the number of edges between each pair of subgraphs
#' @param no.uncon a logical, if TRUE nodes with zero edges are not permitted (each isolated node is assigned one edge)
#' @param link.all a logical, if TRUE all module pairs receive inter-module edges; if FALSE modules are linked in a chain
#' @param p.edge a numeric between 0 and 1, the probability of an edge between any two nodes within a module (Erdos-Renyi only)
#' @param power an integer, the power parameter for scale-free graph generation via preferential attachment
#' @param z.appeal an integer, the zero-appeal parameter controlling the attractiveness of isolated nodes in scale-free generation
#' @param ... additional arguments passed to the underlying igraph graph-building functions

#' @return an igraph object

#' @importFrom igraph sample_gnp sample_pa V add_edges simplify

#' @export
make_submodular_graph <- function(g.type=c("er", "sf"),
                                  n.mods=3, n.mod.links=3,
                                  n.sg=3, n.sg.nodes=120, n.sg.links=1,
                                  no.uncon =T, link.all = T,
                                  p.edge = 0.05, power=1, z.appeal=1, ...){

  # match args
  g.type <- match.arg(g.type)

  # initialize and empty list of subgraphs
  subgraphs <- vector(mode = "list", length = n.sg)

  # create subgraphs and add them to the list
  for (i in 1:n.sg) {
    # create modular graph: er or sf
    temp <- make_modular_graph(g.type=g.type,
                               n.mods=n.mods, n.nodes=n.sg.nodes, n.mod.links=n.mod.links,
                               no.uncon =no.uncon, link.all = link.all,
                               p.edge = p.edge, power=power, z.appeal=z.appeal) # , ...
    # add subgraph label
    igraph::V(temp)$subgraph <- i

    # fix module lables
    mod.names <- paste0(i, ".", letters[1:n.mods]) # cant have more than 26 modules or this breaks down
    temp <- .label_mods(temp, n.sg.nodes, n.mods, mod.names)

    # and node names
    igraph::V(temp)$name <- paste0("Subgraph_", as.character(i) , "_",igraph::V(temp)$name)

    if(no.uncon){
      # check for unconnected nodes
      no.edge <-  igraph::V(temp)[igraph::degree(temp) == 0]

      # if any exist
      if(length(no.edge) > 0){
        # give them each an edge
        for(node in no.edge){
          # get module
          temp.mod <- igraph::V(temp)$module[node]

          # get targets
          targets <- igraph::V(temp)[igraph::V(temp)$module == temp.mod]
          targets <- targets[!(targets %in% no.edge)]

          # add edge
          temp <- igraph::add_edges(temp, c(node, sample(targets, 1)))
        }
      }
    }
    # add to list
    subgraphs[[i]] <- temp
  }

  # merge subgraphs
  hybrid <- do.call(igraph::union, subgraphs)
  igraph::V(hybrid)$name <- unlist(lapply(subgraphs, function(x) igraph::V(x)$name))
  igraph::V(hybrid)$subgraph <- unlist(lapply(subgraphs, function(x) igraph::V(x)$subgraph))

  if(link.all){
    # add edges between each pair of modules
    mod.pairs <- utils::combn(1:n.sg, m = 2, simplify = F)
  }else{
    mod.chain <- c(1:n.sg)
    mod.pairs <- mapply(c, mod.chain, c(mod.chain[-1], mod.chain[1]), SIMPLIFY = FALSE)
  }
  for (pair in mod.pairs) {
    # get node indexes based on subgraphs
    i.nodes <- which(igraph::V(hybrid)$subgraph == pair[1]) # first half of pair
    j.nodes <- which(igraph::V(hybrid)$subgraph == pair[2]) # second half of nodes
    # link i and j by adding edges between random nodes
    hybrid <- igraph::add_edges(hybrid,
                                as.vector(
                                  rbind(
                                    sample(i.nodes, n.sg.links, replace =  T),
                                    sample(j.nodes, n.sg.links, replace =  T)
                                  )
                                )
    )
  }

  # remove duplicate edges and self-loops created during random linking
  hybrid <- igraph::simplify(hybrid, remove.multiple=TRUE, remove.loops=TRUE)
  return(hybrid)
}

#' Helper to label the modules of a graph generated by make_modular_graph
#' @param g an igraph object whose nodes are to be labeled with module membership
#' @param n.nodes an integer, the total number of nodes in the graph
#' @param n.mods an integer, the number of modules in the graph
#' @param mod.names a character vector of length n.mods, the module label for each module

#' @return an igraph object with labeled modules for each node
#' @keywords internal
.label_mods <- function(g, n.nodes, n.mods, mod.names){
  label.start <- 1
  for(i in 1:n.mods){
    igraph::V(g)[label.start:((n.nodes / n.mods)*i)]$module <- mod.names[i]
    label.start <- (n.nodes / n.mods)*i + 1
  }
  return(g)
}



#' Detect co-expression modules from a data matrix using Markov Clustering (MCL)
#' @param x a numeric matrix with p features (rows) and n samples (columns)
#' @param beta an integer, the soft-thresholding power for WGCNA::adjacency
#' @param cut a numeric between 0 and 1, the adjacency threshold used to binarize the weighted adjacency matrix
#' @param expansion an integer, the expansion parameter of the MCL algorithm
#' @param inflation an integer, the inflation parameter of the MCL algorithm
#' @param cor.fn a character, the correlation function to use in WGCNA::adjacency; either 'bicor' or 'cor'
#' @param iter an integer, the maximum number of iterations for the MCL algorithm

#' @return a module object

#' @importFrom methods new

#' @export
find_mcl_mods <- function(x,
                          beta=6,
                          cut=0.05,
                          expansion=2,
                          inflation=1,
                          cor.fn="cor",
                          iter=1000){
  if (!requireNamespace("WGCNA", quietly = TRUE)) {
    stop("Package WGCNA is required. Install with: install.packages('WGCNA')", call. = FALSE)
  }
  if (!requireNamespace("MCL", quietly = TRUE)) {
    stop("Package MCL is required. Install with: install.packages('MCL')", call. = FALSE)
  }
  # compute unsigned and scaled correlation matrix
  mat <- WGCNA::adjacency(datExpr=x,
                          power=beta,
                          corFnc=cor.fn,
                          type="unsigned")

  # convert to adjacency matrix with cut point
  adj <- mat
  adj[mat >= cut] <- 1
  adj[mat < cut] <- 0
  diag(adj) <- 0

  # markov clustering
  clusters <- MCL::mcl(x=as.matrix(adj),
                       addLoops=TRUE,
                       allow1=FALSE,
                       ESM=FALSE,
                       max.iter=iter,
                       expansion=expansion,
                       inflation=inflation)

  # create module object
  mcl.mods <-methods::new("module",
                          source = "mcl",
                          data.dim = dim(t(x)),
                          overlapping = FALSE,
                          index.vector = clusters$Cluster,
                          index.list =split(1:ncol(x) , clusters$Cluster),
                          name.list = split(colnames(x), clusters$Cluster))

  # return Modules
  return(mcl.mods)
}


#' Detect co-expression modules from a data matrix using MEGENA
#' @param x a numeric matrix with p features (rows) and n samples (columns)
#' @param method a character, the correlation method passed to MEGENA::calculate.correlation
#' @param fdr.cutoff a numeric, the FDR cutoff used in MEGENA::calculate.correlation
#' @param mod.pval a numeric, the module significance p-value threshold for MEGENA::do.MEGENA
#' @param hub.pval a numeric, the hub significance p-value threshold for MEGENA::do.MEGENA
#' @param cor.perm an integer, the number of permutations used in MEGENA::calculate.correlation
#' @param hub.perm an integer, the number of permutations used for hub identification in MEGENA::do.MEGENA
#' @param min.size an integer, the minimum number of nodes allowed in a module
#' @param is.signed a logical, if TRUE signed correlation is used in MEGENA::calculate.correlation
#' @param n.cores an integer, the number of cores to use for parallel processing

#' @return a module object

#' @importFrom parallel makeCluster
#' @importFrom doParallel registerDoParallel
#' @importFrom igraph graph.data.frame
#' @importFrom methods new

#' @export
find_megena_mods <- function(x,
                             method="pearson",
                             fdr.cutoff=0.05,
                             mod.pval=0.05,
                             hub.pval=0.05,
                             cor.perm=10,
                             hub.perm=100,
                             min.size=20,
                             is.signed=FALSE,
                             n.cores = 1
){
  if (!requireNamespace("MEGENA", quietly = TRUE)) {
    stop("Package MEGENA is required. Install with: install.packages('MEGENA')", call. = FALSE)
  }

  # if given access to multiple cores...
  do.par <- n.cores > 1
  if (do.par) {
    cl <- parallel::makeCluster(n.cores)
    doParallel::registerDoParallel(cl)
    on.exit(parallel::stopCluster(cl))
  }

  ijw <- MEGENA::calculate.correlation(x,
                                       doPerm=cor.perm,
                                       doPar=do.par,
                                       num.cores=n.cores,
                                       FDR.cutoff=fdr.cutoff,
                                       method=method,
                                       is.signed=is.signed,
                                       output.permFDR=FALSE,
                                       output.corTable=FALSE)

  # calculate planar filtered network (PFN)
  el <- MEGENA::calculate.PFN(ijw[,1:3], keep.track=FALSE)
  gd <- igraph::graph.data.frame(el, directed=FALSE)

  # create modules
  megena <- MEGENA::do.MEGENA(gd,
                              mod.pval=mod.pval,
                              hub.pval=hub.pval,
                              remove.unsig=TRUE,
                              min.size=min.size,
                              max.size=igraph::vcount(gd)/2,
                              doPar=do.par,
                              num.cores=n.cores,
                              n.perm=hub.perm,
                              save.output=FALSE)

  # compute modules statistics and summary
  meg.mods <- MEGENA::MEGENA.ModuleSummary(megena,
                                           mod.pvalue=mod.pval,
                                           hub.pvalue=hub.pval,
                                           min.size=min.size,
                                           max.size=igraph::vcount(gd)/2,
                                           output.sig=TRUE)

  # create module object
  meg.mods <- methods::new("module",
                           source = "megena",
                           data.dim = dim(x),
                           overlapping = TRUE,
                           index.list =lapply(meg.mods$modules, function(mod) which(rownames(x) %in% mod)),
                           name.list = meg.mods$modules)

  # return modules
  return(meg.mods)
}

#' Detect modules using ICA then subdivide any modules exceeding a maximum size
#' @param x a numeric matrix with p features (rows) and n samples (columns)
#' @param max.size an integer, the maximum number of nodes allowed in any single module
#' @param n.mods an integer, the number of independent components to extract; if NULL it is selected automatically

#' @return a module object

#' @importFrom methods new

#' @export
pragmatic_modules <- function(x, max.size, n.mods = NULL){
  if (!requireNamespace("fastICA", quietly = TRUE)) {
    stop("Package fastICA is required. Install with: install.packages('fastICA')", call. = FALSE)
  }
  # perform ICA
  # n initial modules of max size will cover the entire network
  n.comp <- ifelse(is.null(n.mods),
                   ceiling(ncol(t(x)) / max.size), n.mods)

  ICA.results <- fastICA::fastICA(X= x,
                                  n.comp = n.comp,
  )
  comp.score <- abs(ICA.results$S)

  # assign each module the best components
  modules <- apply(comp.score, 1, which.max)
  modules <- split(1:ncol(t(x)), modules)

  # trim to max size
  modules <- lapply(seq_along(modules), function(i){
    mod <- modules[[i]] # get module values
    mod <- mod[order(comp.score[mod,i], decreasing = T)] # order by decreasing score
    mod <- mod[1:max.size] # take only the first max.size values
    mod[!is.na(mod)] # return those that arent na (in case it is shorter than max.size)
  })

  # find unassigned nodes
  unassigned <- which(!(1:ncol(t(x)) %in% unlist(modules)))

  if(length(unassigned) > 0){
    # order based on strength of componet scores
    unassigned <- unassigned[order(rowSums(comp.score[unassigned,]), decreasing = T)]

    mod.sizes <- unlist(lapply(modules, length))
    full.mods <- mod.sizes >= max.size
    for(i in unassigned){
      # determine the best, non full mod
      tmp <- comp.score[i,]
      best.mod <- which(tmp == max(comp.score[i, !full.mods]))
      # add to module and increase its size
      modules[[best.mod]][mod.sizes[best.mod] + 1] <- i # i index will be the same as the order of input data
      mod.sizes[best.mod] = mod.sizes[best.mod] + 1

      # determine if module is full
      if(mod.sizes[best.mod] >= max.size){
        full.mods[best.mod] <- TRUE
      }
    }
  }

  # reformat to get index and score vector from modules index list
  index.vector = vector(mode = "numeric", length = nrow(x))
  score.vector = vector(mode = "numeric", length = nrow(x))
  for(i in seq_along(modules)){
    mod <-  modules[[i]]
    index.vector[mod] <- i
    score.vector[mod] <- comp.score[mod,i]
  }

  # convert to module object and return
  prag.mods <- methods::new("module",
                            source = "pragmatic_modules",
                            data.dim = dim(x),
                            overlapping = FALSE,
                            index.vector = index.vector,
                            score.vector = score.vector,
                            index.list = modules,
                            name.list = lapply(modules, function(mod){rownames(x)[mod]})
  )
  return(prag.mods)
}


#' Create overlapping modules by merging pairs of non-overlapping modules based on shared nodes
#' @param x a numeric matrix with p features (rows) and n samples (columns)
#' @param input.modules a module S4 object containing the non-overlapping module assignments to expand
#' @param use.eigen a logical, if TRUE module pairs are selected based on eigengene correlation; if FALSE nodewise correlation is used
#' @param best.pairs a logical, if TRUE only the best-correlated module pairs are overlapped; if FALSE all pairs are overlapped

#' @return a module object

#' @importFrom stats cor prcomp
#' @importFrom utils combn
#' @importFrom methods new

#' @export
create_overlap_modules <- function(x, input.modules, use.eigen = TRUE, best.pairs = TRUE){
  # extract input modules index list
  input.indexes <- input.modules@index.list

  # get absolute correlation matrix of all node (absolute only in the case of undirected graphs)
  cor.matrix <- abs(stats::cor(t(x)))

  # create potential pairs list
  p.pairs <- as.data.frame(t(utils::combn(length(input.indexes), 2)))
  if(use.eigen){
    # get eigen genes (first PC)
    mod.eigens <- lapply(input.indexes, function(mod){
      mod.PC <- stats::prcomp(t(x[mod,]), scale. = TRUE)
      mod.PC$x[,1]
    })

    # get eigen covar
    p.pairs$cor <- apply(p.pairs, 1, function(r){
      # get overall mean correlation between each pair of modules
      stats::cor(mod.eigens[[r[1]]], mod.eigens[[r[2]]])

    })
  }else{
    # get score representing the abs correlation between nodes in the modules
    p.pairs$cor <- apply(p.pairs, 1, function(r){
      # get overall mean correlation between each pair of modules
      # mean(cor.matrix[modules[[r[1]]], modules[[r[2]]]])
      max(
        mean(apply(cor.matrix[input.indexes[[r[1]]], input.indexes[[r[2]]]]), 1, max), # row/ col matrix are non symmetric
        mean(apply(cor.matrix[input.indexes[[r[1]]], input.indexes[[r[2]]]]), 2, max) # gives rough measure of overall cor between mods
      )

    })
  }
  p.pairs <- p.pairs[order(p.pairs$cor, decreasing = T),]

  # if only using best pairs
  if(best.pairs){
    # track which items are aleardy in pairs, which rows to keep
    in.pairs = vector(mode = "numeric", length = length(input.indexes))
    keep.rows <- vector(mode = "logical", length = nrow(p.pairs))

    # for each row in the the pair table
    in.pairs[p.pairs[1,1]] <- 1 # set first item to one, so it will remain open to close loop
    for(i in 1:nrow(p.pairs)){
      # check if either item is already in two pairs
      used.twice <- in.pairs[c(p.pairs[i,1],p.pairs[i,2])] >= 2

      # if they are both open
      if(all(!used.twice)){
        # keep the row
        keep.rows[i] <- TRUE

        # iterate the pair
        in.pairs[c(p.pairs[i,1],p.pairs[i,2])] <- in.pairs[c(p.pairs[i,1],p.pairs[i,2])] + 1
      }
    }
    # add a final row: the pair between the two modules that only occure once, the first module and the last (by ordered eigen gene cor)
    p.pairs <- rbind(p.pairs[keep.rows,], c(p.pairs[1,1], which(in.pairs == 1), NA))
  }

  # get overlap mods
  overlap.modules <- lapply(1:nrow(p.pairs), function(i){
    left <- input.indexes[[as.numeric(p.pairs[i,1])]] # get two modules in pair
    right <- input.indexes[[as.numeric(p.pairs[i,2])]]

    # get the correlation of nodes between the two modules
    cor.sub.matrix <- cor.matrix[left, right]

    # get the best nodes from each module: the upper half of row
    left.nodes <- left[order(apply(cor.sub.matrix, 1, max))[1:floor(length(left)/2)]]
    right.nodes <- right[order(apply(cor.sub.matrix, 2, max))[1:floor(length(right)/2)]]

    # return overlap mods
    list(
      index = sort(c(left.nodes,right.nodes)),
      overlap = c(p.pairs[i,1],p.pairs[i,2])
    )
  })
  index.list <- lapply(overlap.modules, function(mod){
    mod$index
  })
  names(index.list) <- unlist(
    lapply(overlap.modules, function(mod){
      as.numeric(paste(mod$overlap[1], mod$overlap[2], sep = "."))
    })
  )

  # combine with initial mods
  index.list <- append(input.modules@index.list, index.list)

  # convert to module object and return
  overlap.modules <- methods::new("module",
                                  source = paste("create_overlap_modules", "generated from", input.modules@source),
                                  data.dim = dim(x),
                                  overlapping = TRUE,
                                  index.list = index.list,
                                  name.list = lapply(index.list, function(mod){rownames(x)[mod]})
  )
  return(overlap.modules)
}
